### ISSUE TITLE
Lijst aanvullen met EnergyAssets die gaan voorkomen in MVP (nodig voor berekening gebiedskosten)

### ISSUE THREAD

**Issue by marliekeverweij** [ZEnMo/HOLON#128]
Deze lijst is nodig zodat we in kaart kunnen brengen of alle kostenkentallen beschikbaar zijn in het ETM voor het berekenen van de totale systeemkosten

**Comment by marliekeverweij** [comment]
@JorritvandenHouten Zou het mischien lukken dit deze week nog te doen? Dat zou fijn zijn, dan kan ik volgende week al starten met het schrijven van de ETM queries: https://github.com/ZEnMo/HOLON-ETM/issues/13

**Comment by JorritvandenHouten** [comment]
Ik ga er mee aan de slag! Ik zet een vinkje in een extra kolom 'in scope MVP', en voeg nog niet opgenomen assets toe onderaan de tabel met een kleurtje.

**Comment by marliekeverweij** [comment]
>Ik ga er mee aan de slag! Ik zet een vinkje in een extra kolom 'in scope MVP', en voeg nog niet opgenomen assets toe onderaan de tabel met een kleurtje.

Super fijn!

**Comment by JorritvandenHouten** [comment]
Lijst is aangevuld, over een paar items is denk ik dus nog wat afstemming met Emiel wenselijk, dus daar heb ik voor nu dan even vraagtekens bij gezet
