### ISSUE TITLE
Berekenen warmtebalans in warmtenet & aansturen warmtebronnen in NetConnection agent category DistrictHeating

### ISSUE THREAD

**Issue by JorritvandenHouten** [ZEnMo/HOLON#86]
Warmtenet-afnemers en producenten zijn gelinkt via de heatnode, waar warmtevraag- en aanbod worden opgeteld. Het warmte-aanbod is daarbij nog niet afhankelijk gemaakt van de vraag of temperatuur in het warmtenetwerk.

**Comment by GillisHommen** [comment]
in de laatste commit zit een eerste versie van zo'n warmtebalans: de energiestroom naar de warmtebuffer is de som van verbruik van het net (de afnemers) en de geleverde warmte van de gasbrander.

**Comment by GillisHommen** [comment]
De warmteproductie van de districtHeating GridConnection is nu afhankelijk van de temperatuur in het bijbehorende warmtebuffer. Echter, deze warmteproductie is nu een simpele aan/uit regeling voor één 'heating system'. Dit moet nog verder uitgebreid worden naar meerdere heating systems en op basis van relevante prikkels
