### ISSUE TITLE
Household en Building other electricity demand profile is nog (slechte) placeholder-data

### ISSUE THREAD

**Issue by JorritvandenHouten** [ZEnMo/HOLON#94]
TODO: goede profielen voor overige elektriciteitsgebruik (verlichting, apparaten etc.) voor households en buildings (offices, stores) bepalen, en invoeren in de juiste excel (db_profiles.xlsx)

**Comment by marliekeverweij** [comment]
FYI: in het ETM worden voor het overige elektriciteitsgebruik de volgende profielen gebruikt voor elk scenario / regio:
- huishoudens: NEDU E1a 
- buildings: NEDU E3a

Deze profielen kunnen via de nieuwe module makkelijk binnenhalen uit het ETM.
[Hier](https://docs.energytransitionmodel.com/main/curves) meer info over alle profielen in het ETM
